version: '3'
services:
  meilisearch:
        image: 'getmeili/meilisearch:latest'
        restart: unless-stopped
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - './data/meilisearch:/data.ms'
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s